server:
  port: 9091
spring:
  kafka:
    bootstrap-servers: 172.20.0.210:9092,172.20.0.211:9092,172.20.0.212:9092
    consumer:
      # 配置消费者消息offset是否自动重置(消费者重连会能够接收最开始的消息)
      auto-offset-reset: earliest
      enable-auto-commit: false
kafka:
  topic:
    my-topic1: my-topic1
    my-topic2: my-topic2
    my-topic3: my-topic3